### ISSUE TITLE
bounding range

### ISSUE THREAD

**Issue by peoplestealusernames** [SekiAlpha/Section-7-IT-Map#11]
some objects on the bounding range are floating in mid air or slightly above the ground

**Comment by SekiAlpha** [comment]
Fixed in 2ecadec05684a0e1bc06024d137de2cd299609bd

But Micha mentioned that he wants a bounding range on an MSR.

**Comment by peoplestealusernames** [comment]
iam just move it to the runway and call it fixed when i update it

**Comment by peoplestealusernames** [comment]
moved and fixed
