### ISSUE TITLE
rifle qual

### ISSUE THREAD

**Issue by peoplestealusernames** [SekiAlpha/Section-7-IT-Map#14]
every hit/miss is printed in chat for everyone to see but the final value does not have a name with it also add more ranges

**Comment by peoplestealusernames** [comment]
changed / fixed need to and more ranges

**Comment by SekiAlpha** [comment]
Pretty sure this has been solved, @peoplestealusernames can you confirm?

**Comment by peoplestealusernames** [comment]
Qual remade more ranges can be pasted and hint/print has been fixed
