### ISSUE TITLE
Reset-able targets in Killhouses

### ISSUE THREAD

**Issue by mdx97** [SekiAlpha/Section-7-IT-Map#2]
It would be nice to have targets stay down in the killhouses, and to have the ability to reset all the targets into an upright position. This way targets aren't popping back up after they have been shot during breaching training.

**Comment by peoplestealusernames** [comment]
will look into at a latter date for now the only thing i can think of is to change there can pop variable see: https://forums.bohemia.net/forums/topic/202576-controlling-pop-up-targets-and-counting-accuracy/

**Comment by peoplestealusernames** [comment]
added a pop-up target controller
