### ISSUE TITLE
Ace medical section

### ISSUE THREAD

**Issue by SekiAlpha** [SekiAlpha/Section-7-IT-Map#3]
AI Unconsciousness should be turned 
Medical AI and put armor on them

**Comment by peoplestealusernames** [comment]
ill add a option to copy load outs onto them and turn it on for ai or set the ai to players

**Comment by peoplestealusernames** [comment]
@SekiAlpha i changed the mission settings you need to change the server

**Comment by SekiAlpha** [comment]
Will do in a bit

**Comment by SekiAlpha** [comment]
Okay seems like everything is working now
